create directory controllers and file user
Ryuuket/blog pull request #56
Opened 2023-11-24 14:10 UTC by Noemie34230

J'ai créé une class ControllerUser avec Eric j'ai récupéré la logique qui était dans index.ts.

2023-11-24 14:20 UTC, ecorbisierSimplon approved these changes
this is excellent work

2023-11-24 14:29 UTC, ecorbisierSimplon requested changes
Rename file user.ts in name classe

2023-11-24 14:38 UTC, ecorbisierSimplon approved these changes
It's very good changing

2023-11-28 23:23 UTC, FrankTheHunter commented
👍

2023-11-29 08:41 UTC, Ryuuket approved these changes
Seems good.

2023-11-29 08:42 UTC, merged